In [13]:
import numpy as np
import matplotlib.pyplot as pt

In [16]:
a=np.array([1,2,3])
b=np.array([4,5,6])

## Somme des vecteurs

In [17]:
print(a+b)
print(a-b)
print(a==b)

[5 7 9]
[-3 -3 -3]
[False False False]


In [21]:
np.append(a,b)

array([1, 2, 3, 4, 5, 6])

In [ ]:
pt